### ISSUE TITLE
geekodoc only: Restrict IDs to only alphanumeric characters + "-"

### ISSUE THREAD

**Issue by sknorr** [openSUSE/geekodoc#73]
For SEO reasons, we have decided to abolish all uses of `.` and `_` characters in our DocBook IDs and replace them with `-`.

However, the Geekodoc schema currently allows IDs with `.` and `_` characters in them, so that is not ideal in terms of editing support against our accumulated 100+ years of muscle memory creating IDs with `.` and `_`.

**Comment by sknorr** [comment]
Fwiw, there is now a Travis check against such IDs, so *most* of our documents are now checked for this.

**Comment by sknorr** [comment]
Maybe it is not such a good idea to do that in the schema and the Travis-based solution is better suited for this issue anyway because it is less fix than the schema and because we'd immediately invalidate a ton of existing documents that validated before.

I almost think we should close this one. @tomschr ?

**Comment by tomschr** [comment]
@sknorr 

I can understand that it gives mixed feelings (because it invalidates valid documents). Same with me. :wink: Mabye we should discuss this personally. I provide some thoughts.

Nevertheless, I think it is a good idea. I run into the trap with one of my files and asking myself what I did wrong. I found it later in Travis. IMHO, I think, we shouldn't have two validations which exists in parallel: a local one and a remote one in Travis. Both should report the same (there may be valid exception to this rule). So faster reporting of such errors is a good thing.

On the other side, I see the problem of former documents. With this change they may be invalid now. This is probably a bad thing. However, we could do:

* Raise the major version of Geekodoc to indiciate, there is an incompatible change.
* Communicate the change on doku-intern, get feedback, raise awareness etc.
* Write a conversation script (XSLT, bash, ...) which converts all attribute values of `xml:id` and `linkend` into the correct content. Didn't you do that already?

We could also deal with this change on a packaging level. For example, we could introduce a `geekodoc2` package which could co-exist with the (now) old `geekodoc`. Same like with DocBook 4.x and 5.x. They all co-exist peacefully.

I would suggest, let's discuss this in person (faster, easier). :+1:

**Comment by tomschr** [comment]
Revisiting this issue in the light of openSUSE/daps#566. To use the [ID checks in Travis](https://github.com/openSUSE/doc-ci/blame/master/travis/travis.sh#L301-L302) this can be replicated in GeekoDoc as well.
Tested it with this snippet of RNC code:

```
include "docbookxi.rnc"
{
   db.xml.id.attribute =
     ## Identifies the unique ID value of the element
     attribute xml:id {
      xsd:ID  { pattern = "[\-a-zA-Z0-9]+" } }
}
```

It validates an xml:id of `foo-bar` successfully, but not `foo.bar`.

**Comment by sknorr** [comment]
That is imo definitely a better solution than using DAPS itself for this purpose, thanks. Regex looks good too.
